---
title: "accessingGEDI"
author: "Sam Watson"
date: "April 8, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

Package Insallation
```{r}
library(rGEDI)
library(sf)
library(sp)
```

load AOI data
```{r}
data("studyarea")
aoi <- studyarea$aoi
st_bbox(aoi)
#bolunding box coordinates
ul_lat<- -7.999644
lr_lat<- -9.437084
ul_lon<- -74.099156
lr_lon<- -76.157869
#Data Range
daterange=c("2019-07-10","2020-07-15")
#Get path to GEDI
gLevel1B<-gedifinder(product="GEDI01_B",ul_lat, ul_lon, lr_lat, lr_lon,version="001",daterange=daterange)
gLevel2A<-gedifinder(product="GEDI02_A",ul_lat, ul_lon, lr_lat, lr_lon,version="001",daterange=daterange)
gLevel2B<-gedifinder(product="GEDI02_B",ul_lat, ul_lon, lr_lat, lr_lon,version="001",daterange=daterange)
```

Downloading the data
```{r}
outdir = "F:\\R_Project\\July_2019"
gediDownload(filepath=gLevel1B,outdir=outdir)
gediDownload(filepath=gLevel2A,outdir=outdir)
gediDownload(filepath=gLevel2B,outdir=outdir)
```

reading GEDI data
```{r}
# Reading GEDI data
gedilevel1b<-readLevel1B(level1Bpath = paste0(outdir,"\\GEDI01_B_2019195233920_O03325_T05109_02_003_01.h5"))
gedilevel2a<-readLevel2A(level2Apath = paste0(outdir,"\\GEDI02_A_2019195233920_O03325_T05109_02_001_01.h5"))
gedilevel2b<-readLevel2B(level2Bpath = paste0(outdir,"\\GEDI02_B_2019195233920_O03325_T05109_02_001_01.h5"))
```

GEDI pulse location level 1B
```{r}
level1bGeo<-getLevel1BGeo(level1b=gedilevel1b,select=c("elevation_bin0"))
head(level1bGeo)


# Converting shot_number as "integer64" to "character"
level1bGeo$shot_number<-paste0(level1bGeo$shot_number)

# Converting level1bGeo as data.table to SpatialPointsDataFrame
library(sp)
level1bGeo$longitude_bin0[is.na(level1bGeo$longitude_bin0)] <- 0
level1bGeo$latitude_bin0[is.na(level1bGeo$latitude_bin0)] <- 0

level1bGeo_spdf<-SpatialPointsDataFrame(cbind(level1bGeo$longitude_bin0, level1bGeo$latitude_bin0),
                                        data=level1bGeo)

# Exporting level1bGeo as ESRI Shapefile
raster::shapefile(level1bGeo_spdf,paste0(outdir,"\\GEDI01_B_2019108080338_O01964_T05337_02_003_01_sub"))
```

