---
title: "Using_rGEDI"
author: "Amanda Payton"
date: "April 14, 2020"
output: html_document
---

Installation
```{r}
#install.packages("rGEDI")
library(rGEDI)
library(geospaar)
library(sf)
library(ggplot2)
library(sp)

```

Area of Interest and Setup
```{r}
#load data
data("studyarea")

#get bounding box coordinates
st_bbox(studyarea$aoi)

#set parameters for coordinates
ul_lat <- -7.999644   #ymax
lr_lat <- -9.437084 #ymin
lr_lon <- -76.157869 #xmin
ul_lon <- -74.099156  #xmax

#pick date range
daterange = c("2019-08-01", "2019-09-01")

outdir = "C:/Users/Amanda/Documents/gediamazonia/data"

```

Get Data
```{r}
# Get path to GEDI data

#Level 1B Geolocated Waveforms
#gLevel1B <- gedifinder(product = "GEDI01_B", ul_lat, ul_lon, lr_lat, lr_lon, version = "001", daterange = daterange)

#Level 2A Elevation and Height Metrics
gLevel2A <- gedifinder(product = "GEDI02_A", ul_lat, ul_lon, lr_lat, lr_lon, version = "001", daterange = daterange)

#Level 2B Canopy Cover and Vertical Profile Metrics
#gLevel2B <- gedifinder(product = "GEDI02_B", ul_lat, ul_lon, lr_lat, lr_lon, version = "001", daterange = daterange)

#Download

#gediDownload(filepath = gLevel1B, outdir = outdir)
gediDownload(filepath = gLevel2A, outdir = outdir)
#gediDownload(filepath = gLevel2B, outdir = outdir)

```

Read Data and Get Full-Waveform data
```{r}
#read in data

#gedilevel1b <- readLevel1B(level1Bpath = file.path(outdir, "GEDI01_B_2019216034003_O03638_T04321_02_003_01.h5"))

gedilevel2a_1 <- readLevel2A(level2Apath = file.path(outdir, "GEDI02_A_2019214160606_O03615_T03487_02_001_01.h5"))

gedilevel2a_2 <- readLevel2A(level2Apath = file.path(outdir, "GEDI02_A_2019216034003_O03638_T04321_02_001_01.h5"))

#gedilevel2b <- readLevel2B(level2Bpath = file.path(outdir, "GEDI02_B_2019108080338_O01964_T05337_02_001_01_sub.h5"))


#Get Full-Waveform Geolocation
#level1bGeo <- getLevel1BGeo(level1b = gedilevel1b, select = c("elevation_bin0"))
#head(level1bGeo)

#Get Elevation and Height Metrics
level2aGeo_1 <- getLevel2AM(gedilevel2a_1)
head(level2aGeo_1[,c("beam","shot_number","elev_highestreturn","elev_lowestmode","rh100")])

level2aGeo_2 <- getLevel2AM(gedilevel2a_2)
head(level2aGeo_1)#[,c("beam","shot_number","elev_highestreturn","elev_lowestmode","rh100")])

```

Convert Level 1b to spatial data frame and export as shapefile
```{r}
# Converting shot_number as "integer64" to "character"
#level1bGeo$shot_number <- paste0(level1bGeo$shot_number)


#convert NA values in coordinates to 0
#level1bGeo$longitude_bin0[is.na(level1bGeo$longitude_bin0)] <- 0
#level1bGeo$latitude_bin0[is.na(level1bGeo$latitude_bin0)] <- 0


# Converting level1bGeo as data.table to SpatialPointsDataFrame
#library(sp)
#level1bGeo_spdf <- SpatialPointsDataFrame(cbind(level1bGeo$longitude_bin0, 
#                                                level1bGeo$latitude_bin0), 
#                                          data = level1bGeo)

# Exporting level1bGeo as ESRI Shapefile
#raster::shapefile(level1bGeo_spdf,paste0(outdir,"/GEDI01_B"))
```

Convert Level 2A Data to spatial data frame and export as shapefile
```{r}
# Convert shot_number as "integer64" to "character"
#level2aGeo_1$shot_number <- paste0(level2aGeo_1$shot_number)
#level2aGeo_2$shot_number <- paste0(level2aGeo_2$shot_number)

#convert NA values in coordinates to 0
#level2aGeo_1$lon_lowestmode[is.na(level2aGeo_1$lon_lowestmode)] <- 0
#level2aGeo_1$lat_lowestmode[is.na(level2aGeo_1$lat_lowestmode)] <- 0

#level2aGeo_2$lon_lowestmode[is.na(level2aGeo_2$lon_lowestmode)] <- 0
#level2aGeo_2$lat_lowestmode[is.na(level2aGeo_2$lat_lowestmode)] <- 0

# Converting Elevation and Height Metrics as data.table to SpatialPointsDataFrame
#level2A_spdf1 <- SpatialPointsDataFrame(cbind(level2aGeo_1$lon_lowestmode, 
#                                              level2aGeo_1$lat_lowestmode), 
#                                        data = level2aGeo_1)
#level2A_spdf2 <- SpatialPointsDataFrame(cbind(level2aGeo_2$lon_lowestmode, 
#                                              level2aGeo_2$lat_lowestmode), 
#                                        data = level2aGeo_2)

# Exporting Elevation and Height Metrics as ESRI Shapefile
#raster::shapefile(level2A_spdf1, paste0(outdir, "/GEDI02_A1"))
#raster::shapefile(level2A_spdf2, paste0(outdir, "/GEDI02_A2"))

```

Clip shapefile
```{r}

#read in shapefile
#level1bShp <- st_read(dsn = "C:/Users/Amanda/Documents/gediamazonia/data/GEDI01_B.shp")
level2aShp1 <- st_read(dsn = "C:/Users/Amanda/Documents/gediamazonia/data/GEDI02_A1.shp")
level2aShp2 <- st_read(dsn = "C:/Users/Amanda/Documents/gediamazonia/data/GEDI02_A2.shp")

#get AOI coordinate system and set shapefile to that 
reference <- st_crs(studyarea$aoi)
st_crs(level1bShp) <- reference
st_crs(level2aShp1) <- reference
st_crs(level2aShp2) <- reference

#make a polygon with AOI coordinates
coords <- cbind("x" = c(ul_lon, lr_lon, lr_lon, ul_lon, ul_lon), 
                "y" = c(ul_lat, ul_lat, lr_lat, lr_lat, ul_lat))

aoi_bbox <- st_polygon(x = list(coords)) %>% st_sfc %>% st_sf(ID = 1, crs = 4326)
plot(st_geometry(aoi_bbox))

#clip shapefile to AOI polygon
aoi_1bLidar <- st_intersection(x = aoi_bbox, y = level1bShp)
aoi_2aLidar1 <- st_intersection(x = aoi_bbox, y = level2aShp1)
aoi_2aLidar2 <- st_intersection(x = aoi_bbox, y = level2aShp2)

```

Check Bounding Box
```{r}
st_bbox(aoi_bbox)
st_bbox(level1bShp)
st_bbox(studyarea$aoi)


```

Visualize
```{r}
par(mar = c(0, 0, 0, 0))
plot(st_geometry(aoi_1bLidar), col = "grey")
plot(st_geometry(aoi_bbox), add = TRUE)

#plot data showing elevation of lidar data
ggplot() + geom_sf(data = studyarea$np, fill = "blue") + 
  geom_sf(data = studyarea$buffer, fill = "lightblue") + 
  geom_sf(data = studyarea$cacao_zone, color = "red", fill = "transparent") +
  geom_sf(data = studyarea$aoi, color = "purple", fill = "transparent") +
  #geom_sf(data = aoi_1bLidar, aes(color = elvtn_0))
  geom_sf(data = aoi_2aLidar2, aes(color = elv_hgh))
```


